apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-link-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: live-link-backend
  template:
    metadata:
      labels:
        app: live-link-backend
    spec:
      containers:
      - name: live-link-backend
        image: tylerpitcher/live-link-backend:59f3100
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_URI
          value: "redis://live-link-redis-service:6379"
        - name: FRONTEND_URL
          value: "https://www.tylerpitcher.com"
        - name: EXPIRATION
          value: "604800"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: live-link-secret
              key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: live-link-backend-service
spec:
  selector:
    app: live-link-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: live-link-backend-ingress-https
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`tylerpitcher.com`, `www.tylerpitcher.com`) && (PathPrefix(`/api`) || PathPrefix(`/socket`))
    kind: Rule
    services:
    - name: live-link-backend-service
      port: 8000
  tls:
    secretName: tls-secret
