apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: tylerpitcher/live-link-backend:3bdc5f9
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_URI
          value: "redis://redis-service:6379"
        - name: HOST
          value: "https://www.tylerpitcher.com"
        - name: EXPIRATION
          value: "604800"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: live-link-secret
              key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: backend-ingress
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`tylerpitcher.com`, `www.tylerpitcher.com`) && PathPrefix(`/api`)
    kind: Rule
    services:
    - name: backend-service
      port: 8000
  tls:
    secretName: tls-secret
